tokenizer:
  model_name: lvwerra/gpt2-imdb #todo change this
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: True
  new_tokens: [ ' <GPT3>', ' </GPT3>' ]

reward_fn:
  id: meteor

datapool:
  id: cnn_gpt23
  args:
    prompt_prefix: "Summarize this text.\n\n"
    prompt_suffix: "\n\nSummary: "
    data_path: "" #todo finish this


env:
  n_envs: 10
  args:
    max_prompt_length: 900
    max_episode_length: 100
    terminate_on_eos: True

alg:
  id: ppo
  args:
    n_steps: 512
    batch_size: 64
    verbose: 1
    learning_rate: 0.000002
    n_epochs: 3
    ent_coef: 0.0
  kl_div:
    coeff: 0.01
    target_kl: 0.2
  cost_reward:
    prompt_cost: 0.05
    generation_cost: 0.05
  policy:
    id: causal_lm_actor_critic_policy
    args:
      model_name: lvwerra/gpt2-imdb #todo change this
      apply_model_parallel: True
      generation_kwargs:
        do_sample: True
        top_k: 100
        min_length: 50
        max_new_tokens: 100
        use_big_model: True

train_evaluation:
  eval_batch_size: 100
  n_iters: 50
  eval_every: 10
  save_every: 1
  metrics:
    - id: meteor
      args: {}
    - id: rouge
    - id: bleu
      args: {}
    - id: bert_score
      args:
        language: en
    - id: gpt3_numtokens
      args: {}
    # - id: bleurt
    #   args:
    #     config_name: bleurt-large-512
    - id: diversity
      args: {}
    # - id: summaCZS
    #   args:
    #     granularity: sentence
    #     use_ent: True
    #     use_con: False
    # - id: summaCConv
    #   args:
    #     granularity: sentence
