tokenizer:
  model_name: '/data/dheeraj/GPT23/saved_models/gpt2_3_small_wmt16_ft_noprompt_seed_13'
  padding_side: left
  truncation_side: right
  pad_token_as_eos_token: True

reward_fn:
  id: sacre_bleu
  args:
    tokenize: "intl"

datapool:
  id: wmt16newsonly
  args:
    prompt_suffix: "\n"

env:
  n_envs: 8
  args:
    max_prompt_length: 128
    max_episode_length: 128
    terminate_on_eos: True

alg:
  id: ppo
  args:
    n_steps: 128
    batch_size: 16
    verbose: 1
    learning_rate: 0.000001
    n_epochs: 5

  kl_div:
    coeff: 0.001
    target_kl: 0.2

  cost_reward:
    prompt_cost: 0.05
    generation_cost: 0.05
    cost_reward_coeff: 0.4

  policy:
    id: causal_lm_actor_critic_policy
    args:
      model_name: '/data/dheeraj/GPT23/saved_models/gpt2_3_small_wmt16_ft_noprompt_seed_13'
      apply_model_parallel: False
      generation_kwargs:
        do_sample: True
        max_new_tokens: 128
        top_k: 30
        use_big_model: True
        big_model_prompt: "Translate the following sentence from english to german:\n"
        loss_for_big_model: False
        value_eq_policy: True

train_evaluation:
  eval_batch_size: 128
  n_iters: 50
  eval_every: 10
  save_every: 10
  metrics:
    - id: meteor
      args: {}
    - id: rouge
    - id: bleu
      args: {}
#    - id: bert_score
#      args:
#        language: en
    - id: sacre_bleu
      args:
        tokenize: "intl"
    - id: ter
      args: {}
    - id: chrf
      args: {}
    - id: diversity
      args: {}
    - id: gpt3_numtokens
      args: {}
    - id: cost_reward
      args:
        tokenizer_id: '/data/dheeraj/GPT23/saved_models/gpt2_3_small_wmt16_ft_noprompt_seed_13'
        prompt_cost: 0.05
        generation_cost: 0.05
        truncation_side: 'right'
        max_prompt_length: 128